version: '3'

services:
  wordpress:
    build: ./path_to_wordpress_dockerfile
    ports:
      - "8080:80"
    networks:
      - frontend_network
      - backend_network
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mariadb:latest
    networks:
      - backend_network
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: your_password_here

networks:
  frontend_network:
  backend_network:

volumes:
  wordpress_data:
  mariadb_data:
